import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthProvider } from "./context/AuthContext"; // 1. Import කරන්න
import { Toaster } from 'react-hot-toast';
import { WishlistProvider } from "./context/WishlistContext";

// 1. Konfigurera Poppins
const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
  variable: "--font-poppins", // Skapar en CSS variabel
});

// 2. Konfigurera Roboto
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ["latin"],
  variable: "--font-roboto", // Skapar en CSS variabel
});

export const metadata: Metadata = {
  title: "QuickCart - Shopping Made Easy",
  description: "E-commerce platform built with Next.js and Spring Boot",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable} antialiased font-sans`}>
        <AuthProvider> {/* 2. AuthProvider එකෙන් ඔතන්න */}
          <Toaster position="top-center" reverseOrder={false}/>
            <WishlistProvider> {/* 2. මෙතනින් ඔතන්න */}
            <Toaster position="top-center" reverseOrder={false}/>
            {children}
          </WishlistProvider>
        </AuthProvider>
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }